[project]
name = "web-llm-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckduckgo-search>=6.3.5",
    "httpx>=0.27.2",
    "requests>=2.32.3",
    "rich>=13.9.4",
    "typer>=0.13.1",
]
